# async 와 await 사용하기

기존 promise 는
axios,get(url)
.then().catch()

를 사용하여 예외처리를 하였다.

<br/>

async와 await는 try catch를 이용하여 예외 처리를 하면된다.
